on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: 1
        env:
          UPDATE_1: ${{ secrets.UPDATE_1 }}
        run: |
          wget ${{ secrets.UPDATE_1 }}